=== WormBase/website-intermine-sources-DEPRECATED/intermine/intermine-0.96/intermine/MineManager/installer/src/main/xsd/sourcedescriptor.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
            xmlns:sd="http://flymine.org/sourcedescriptor/1.0"
            targetNamespace="http://flymine.org/sourcedescriptor/1.0"
            jaxb:extensionBindingPrefixes="xjc"
            jaxb:version="2.0">
            
    <xsd:annotation>
        <xsd:documentation>
            The source descriptor schema defines how data sources should be described
            for the Intermine installer. Each data source added to Intermine should have
            an implementation of this.
        </xsd:documentation>

        <xsd:appinfo>
            <jaxb:globalBindings>
                <xjc:serializable uid="1"/>
            </jaxb:globalBindings>
        </xsd:appinfo>
    </xsd:annotation>

    <xsd:element name="source" type="sd:sourceDescriptor">
        <xsd:annotation>
            <xsd:documentation>
                The outermost element; an implementation of sourceDescriptor.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="sourceDescriptor">
        <xsd:annotation>
            <xsd:documentation>
                The source descriptor lists the properties the data source requires from the
                user when it is set up. It may also indicates by the derivation section, that this
                source type needs to be derived to create a specific instance of its type. 
            </xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="property" type="sd:propertyDescriptor" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>
                        A normal property required to configure the data source.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            
            <xsd:element name="derivation" type="sd:sourceTypeDerivation" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        An optional section indicating that this type is not a true data type,
                        but requires a new source type to be created like this type.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        
        <xsd:attribute name="type" type="xsd:ID" use="required">
            <xsd:annotation>
                <xsd:documentation>
                    The name of this source type.
                    This should match the XML file name (less the .xml suffix).
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="propertyDescriptor">
        <xsd:annotation>
            <xsd:documentation>
                The description of a configuration property in a data source.
            </xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="validation" type="xsd:string" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        An optional regular expression that values for this property must
                        match to be valid.
                        This is an element rather than an attribute to allow the use of
                        CDATA sections.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        
        <xsd:attribute name="name" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>
                    The name of the configuration property.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        
        <xsd:attribute name="required" type="xsd:boolean" use="optional" default="false">
            <xsd:annotation>
                <xsd:documentation>
                    Flag indicating this property must have a value.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        
        <xsd:attribute name="type" type="sd:propertyType" use="optional" default="string">
            <xsd:annotation>
                <xsd:documentation>
                    The type for this property. Must be one of the propertyType values.
                    The propertyType "string" should be inferred if this attribute is not defined.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        
        <xsd:attribute name="extension" type="xsd:string" use="optional" >
            <xsd:annotation>
                <xsd:documentation>
                    The extension to use to filter files against in a chooser
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>

        <xsd:attribute name="hidden" type="xsd:boolean" use="optional" default="false">
            <xsd:annotation>
                <xsd:documentation>
                    Flag indicating that this property should not be made visible to the user
                    of the Intermine installer.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="propertyType">
        <xsd:annotation>
            <xsd:documentation>
                An enumeration of the possible types for configuration properties.
            </xsd:documentation>
        </xsd:annotation>

        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="string">
                <xsd:annotation>
                    <xsd:documentation>
                        Property is a plain character string.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            
            <xsd:enumeration value="boolean">
                <xsd:annotation>
                    <xsd:documentation>
                        Property is a boolean value.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            
            <xsd:enumeration value="integer">
                <xsd:annotation>
                    <xsd:documentation>
                        Property is an integer value.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>

            <xsd:enumeration value="decimal">
                <xsd:annotation>
                    <xsd:documentation>
                        Property is a decimal value.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>

            <xsd:enumeration value="class">
                <xsd:annotation>
                    <xsd:documentation>
                        Property is the name of a qualified Java class.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            
            <xsd:enumeration value="file">
                <xsd:annotation>
                    <xsd:documentation>
                        Property indicates a file on the file system.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            
            <xsd:enumeration value="directory">
                <xsd:annotation>
                    <xsd:documentation>
                        Property indicates a directory on the file system.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="sourceTypeDerivation">
        <xsd:annotation>
            <xsd:documentation>
                The derivation section indicates that the data source should be used to create
                a new, true data source.
            </xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="property" type="sd:propertyDescriptor" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>
                        Additional properties needed when creating the source. These are passed
                        to the make_source script as additional arguments.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        
        <xsd:attribute name="antTask" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>
                    The name of the property in the Ant build properties file that indicates
                    the data source is indeed the type of source expected.
                    The Ant properties file is "project.properties" in the data source directory.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== WormBase/website-intermine-sources-DEPRECATED/intermine/intermine-0.96/intermine/MineManager/installer/src/main/resources/org/intermine/install/project/sources/chado-db.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sd:source xmlns:sd="http://flymine.org/sourcedescriptor/1.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://flymine.org/sourcedescriptor/1.0 http://www.flymine.org/download/schemas/sourcedescriptor.xsd"
           type="chado-db">

    <property name="source.db.name" required="true" />
    <property name="genus" required="true" />
    <property name="species" required="true" />
    <property name="taxonId">
        <validation><![CDATA[^\d+(\s\d+)*$]]></validation>
    </property>
    <property name="dataSourceName" />
    <property name="dataSetTitle" />
    <property name="processors" type="class" />
    
    <derivation antTask="have.db.tgt" />

</sd:source>
